package com.mg.community.model;

import java.io.Serializable;

public class Sysparam implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysparam.id
     *
     * @mbg.generated Sun Mar 01 15:42:22 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysparam.redis
     *
     * @mbg.generated Sun Mar 01 15:42:22 CST 2020
     */
    private String redis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysparam.private_key
     *
     * @mbg.generated Sun Mar 01 15:42:22 CST 2020
     */
    private String privateKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysparam.public_key
     *
     * @mbg.generated Sun Mar 01 15:42:22 CST 2020
     */
    private String publicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sysparam
     *
     * @mbg.generated Sun Mar 01 15:42:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysparam.id
     *
     * @return the value of sysparam.id
     *
     * @mbg.generated Sun Mar 01 15:42:22 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysparam.id
     *
     * @param id the value for sysparam.id
     *
     * @mbg.generated Sun Mar 01 15:42:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysparam.redis
     *
     * @return the value of sysparam.redis
     *
     * @mbg.generated Sun Mar 01 15:42:22 CST 2020
     */
    public String getRedis() {
        return redis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysparam.redis
     *
     * @param redis the value for sysparam.redis
     *
     * @mbg.generated Sun Mar 01 15:42:22 CST 2020
     */
    public void setRedis(String redis) {
        this.redis = redis == null ? null : redis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysparam.private_key
     *
     * @return the value of sysparam.private_key
     *
     * @mbg.generated Sun Mar 01 15:42:22 CST 2020
     */
    public String getPrivateKey() {
        return privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysparam.private_key
     *
     * @param privateKey the value for sysparam.private_key
     *
     * @mbg.generated Sun Mar 01 15:42:22 CST 2020
     */
    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey == null ? null : privateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysparam.public_key
     *
     * @return the value of sysparam.public_key
     *
     * @mbg.generated Sun Mar 01 15:42:22 CST 2020
     */
    public String getPublicKey() {
        return publicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysparam.public_key
     *
     * @param publicKey the value for sysparam.public_key
     *
     * @mbg.generated Sun Mar 01 15:42:22 CST 2020
     */
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey == null ? null : publicKey.trim();
    }
}